name: wispurr
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  image: ^4.1.3  # For image processing
  permission_handler: ^12.0.1
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.13.1
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  bloc: ^9.0.0
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/
    - assets/icons/       # Icons for the app
    - assets/images/      # Images for the app
    - assets/models/      # ML models for the app
    - .env                # Environment variables

  