name: wispurr
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  image: ^4.1.3  # For image processing
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/
    - assets/icons/       # Icons for the app
    - assets/images/      # Images for the app

  